In [1]:
import random

a = 1; b = 6
r1 = random.randint(a, b)   # first die
r2 = random.randint(a, b)   # second die

print('the dice gave: {:d} and {:d}'.format(r1, r2))

the dice gave: 5 and 5


In [10]:
import random

random.seed(10)

random.randint(1, 6)

5

In [11]:
random.randint(1, 6)

1

In [12]:
import random

x = random.random()         # draw float from [0, 1] assign to x

y = random.uniform(10, 20)  # ...float from [10, 20] assign to y

print('x = {:g}, y = {:g}'.format(x, y))

x = 0.428889, y = 15.7809


In [13]:
import numpy as np

np.random.randint(1, 6, 4)  # ...4 integers from [1, 6]

array([1, 3, 1, 5])

In [14]:
np.random.random(4)         # ...4 floats from [0, 1]

array([0.44686303, 0.91977953, 0.01094726, 0.44177725])

In [16]:
np.random.uniform(10, 20, 4)    # ...4 floats from [10, 20]

array([17.20210035, 15.07425093, 19.56181978, 18.03503064])

In [17]:
import numpy as np

a = np.array([1, 2, 3, 4])

np.random.shuffle(a)

a

array([4, 3, 1, 2])